### ISSUE TITLE
The ::set-output:: function is deprecated

### ISSUE THREAD

**Issue by donfirst** [badsyntax/github-action-aws-cloudformation#202]
Describe the feature

The ::set-output:: function is deprecated in favor of using the GITHUB_OUTPUT environment file

Use Case

The set-output function is insecure according to this notification: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Other Information

No response

**Comment by badsyntax** [comment]
Thanks for the issue report.

Please try version [v1.0.3](https://github.com/badsyntax/github-action-aws-cloudformation/releases/tag/v1.0.3) (or master)
