### ISSUE TITLE
Input 'parameters' is supposed to be not required but fails when empty / not present

### ISSUE THREAD

**Issue by mattpu-sportsbet** [badsyntax/github-action-aws-cloudformation#63]
action.yml defines required: false for parameters, but the const is set to required=true.

`    const parameters = (0,core.getInput)('parameters', {
        required: true,
        trimWhitespace: true,
    });`

Running this action with out the option parameters: for cloudformation stacks that have no parameters fail. 

Also specifying 'parameters:' with empty values fails as function getInput throws on any empty value.

`Input required and not supplied: parameters`

**Comment by badsyntax** [comment]
Thanks for the bug report. I'll release a fix very soon.

**Comment by mattpu-sportsbet** [comment]
Thanks Richard! Also, hi from the other side of the world from a fellow Yorkshire-man!

**Comment by badsyntax** [comment]
Hey up! :) 

This should be fixed now. Can you try [v1.0.1](https://github.com/badsyntax/github-action-aws-cloudformation/releases/tag/v1.0.1) and let me know if you have any probs?

**Comment by badsyntax** [comment]
Had a few issues publishing the release. v1.0.1 should be available now.

**Comment by mattpu-sportsbet** [comment]
Just ran from master, seems to be working now. 
Getting some errors from the following action (your github-actiion-issue-comment from the downstream 'peter-evans/find-comment@v1' action, but i will troubleshoot tomorrow and follow up on that repo if need be. 
Cheers!
Matt

**Comment by badsyntax** [comment]
Hmm. Let me know once you discover what's going there.

Here's how i use the PR comments action in this repo: https://github.com/badsyntax/github-action-aws-cloudformation/blob/4b5155352c1aed34b796766792ff5d4b4199a4ab/.github/workflows/test-build-deploy.yml#L60-L84

**Comment by mattpu-sportsbet** [comment]
Thanks, I got it working in a workflow dispatch. I think the errors I'm seeing are downstream in one of the sub-actions (rate limiting causing missing comments when running in a matrix), and not related to this issue.
