### ISSUE TITLE
ChangeSet fails to create when CloudFormation requires CAPABILITY_NAMED_IAM

### ISSUE THREAD

**Issue by mattpu-sportsbet** [badsyntax/github-action-aws-cloudformation#85]
https://github.com/badsyntax/github-action-aws-cloudformation/blob/4b5155352c1aed34b796766792ff5d4b4199a4ab/src/cloudformation.ts#L207

**Comment by badsyntax** [comment]
Thanks for the report. Here's some docs on this: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cloudformation/interfaces/createchangesetcommandinput.html#capabilities

I think capabilities should be user defined as an action input. Does that align with your understanding?

I will introduce a new action input to configure this behaviour.

**Comment by mattpu-sportsbet** [comment]
Yeah if we can pass this as a parameter input that would be better I think

**Comment by badsyntax** [comment]
This change is released with [v1.0.2](https://github.com/badsyntax/github-action-aws-cloudformation/releases/tag/v1.0.2)

You can now configure the required capabilities, like so:

https://github.com/badsyntax/github-action-aws-cloudformation/blob/43a944a4f7c3ee74e526f6616d95abcccbef3367/.github/workflows/test-build-deploy.yml#L69

Docs here: https://github.com/badsyntax/github-action-aws-cloudformation/blob/master/README.md#action-inputs

Let me know if this solves things for you.

**Comment by mattpu-sportsbet** [comment]
Works great, thank you!

**Comment by badsyntax** [comment]
Thanks for verifying.
